### PR TITLE
Organized the code

### PR DESCRIPTION
**Pull request by CodeWithSwastik**
I moved the Converter class and convert function to a separate file for better readability. Also added __license__ and __copyright__

### CODE REVIEW

**Comment by NightZan999** [comment]
@BobDotCom, oi you should probably take this. I saw the fork and its awesome!

**Comment by BobDotCom** [comment]
Unfortunately I wanted it to be this way originally, but it completely renders sphinx's auto-documentation useless. Until there is a way that the autodoc can support this, it can't be done.

**Comment by NightZan999** [comment]
So what the hell is autodoc?

**Comment by BobDotCom** [comment]
Autodoc automatically takes docstrings and makes a documentation for it. Apparently it can only see the __init__ file for doing the documentation correctly.

**Comment by NightZan999** [comment]
> Autodoc automatically takes docstrings and makes a documentation for it. Apparently it can only see the __init__ file for doing the documentation correctly.

you could add his code to __init__.py 
;-;

**Comment by BobDotCom** [comment]
> > Autodoc automatically takes docstrings and makes a documentation for it. Apparently it can only see the **init** file for doing the documentation correctly.
> 
> you could add his code to **init**.py
> ;-;

ok maybe

**Pull request closed without merging**
